Updated DEQM for 2024 SEP Ballot
HL7/JIRA-Spec-Artifacts pull request #1075
Opened 2024-08-19 19:17 UTC by brynrhodes

2024-08-19 20:39 UTC, lmckenzi requested changes
SEP should be Sep.

2024-08-20 20:06 UTC, lmckenzi requested changes
Still need to fix the ballotUrl

2024-08-20 20:06 UTC, brynrhodes commented
Done

2024-08-20 20:08 UTC, brynrhodes commented
Also fixed in the publication request

2024-08-21 21:01 UTC, merged